Feat/chat/member
42-TRANSENDENCE/backend pull request #107
Opened 2023-03-30 19:35 UTC by maindishes

- mutelist cache 로 관리 
- 밴 확인후 입장 
- mutelist 확인후 채팅 보내기 가능 
-  초당 동일 ip 로 요청 횟수 제한 ( 민준쿤이 막아놓은 초당 함수 요청 제한이랑 초당 동일 ip요청 횟수 제한 둘다 쓰면 동시에 3명이 여러번 login 누르는거 어느정도 해결 되지 않을까 ???? )

2023-03-31 02:18 UTC, minjune8506 commented on src/channels/chats/chats.controller.ts
>  @ApiTags('CHAT')
Api Tag => CHAT
Controller => room
수정 바람

2023-03-31 02:19 UTC, minjune8506 commented on src/channels/chats/chats.controller.ts
>  @ApiTags('CHAT')
Controller => room
url => channel ID
이상함.
room / channel 중 하나로 통일해서 네이밍을 맞출 것

2023-03-31 02:25 UTC, minjune8506 commented on src/channels/chats/chats.service.ts
> +    console.log(`this is chatsservice ${mutelist}`);
logger로 변경

2023-03-31 02:25 UTC, minjune8506 commented on src/channels/chats/chats.service.ts
> +      if (userId == 1) {
user 연결은 언제쯤?

2023-03-31 02:26 UTC, minjune8506 commented on src/channels/chats/chats.service.ts
> +    this.channelsGateway.nsp.emit('message', chat);
channel에 보내야하는데 nsp.emit?
nsp.to.emit으로 해야하지 않나여?

2023-03-31 02:27 UTC, minjune8506 commented on src/channels/channelbanmember.entity.ts
> +  ChannelId: number;
이것도 channelId 대소문자 구분

2023-03-31 02:27 UTC, minjune8506 commented on src/channels/channelbanmember.entity.ts
> +  UserId: number;
대소문자 구분

2023-03-31 02:28 UTC, minjune8506 commented on src/channels/channelmutemember.entity.ts
> +import { User } from 'src/users/users.entity';
channel ban / mute를 같은 구조로 2개 만들거면
하나로 통일한 후 status 를 enum으로 가지고 ban / mute를 구분하면 어떨까요?

2023-03-31 02:28 UTC, minjune8506 commented on src/channels/channels.controller.ts
> +  @Post('/room/:roomId/ban/:userId')
controller에 room이 있는데 왜 여기에 room이..?

2023-03-31 02:32 UTC, minjune8506 commented on src/channels/channels.service.ts
> +      else {
이 else문도 안쓸수 있을것같네요

2023-03-31 02:32 UTC, minjune8506 commented on src/channels/channels.service.ts
> +      await this.cacheManager.set(key, kicklist, 50000);
50000은 무슨 뜻이죠?

2023-03-31 02:33 UTC, minjune8506 commented on src/channels/channels.service.ts
> +    const ban = await this.channelMuteMemberRepository.findOne({
mute repository에서 가져오는데 변수 이름은 ban..?

2023-03-31 02:34 UTC, minjune8506 requested changes
전체적으로 한번 다시 확인..

2023-03-31 03:46 UTC, maindishes commented on src/channels/chats/chats.service.ts
> +    console.log(`this is chatsservice ${mutelist}`);
변경 완료

2023-03-31 03:53 UTC, maindishes commented on src/channels/channelbanmember.entity.ts
> +  ChannelId: number;
clear

2023-03-31 03:53 UTC, maindishes commented on src/channels/channelbanmember.entity.ts
> +  UserId: number;
clear

2023-03-31 03:54 UTC, maindishes commented on src/channels/channelmutemember.entity.ts
> +import { User } from 'src/users/users.entity';
mute 는 캐시로 관리해서 삭제 하겠슴다

2023-03-31 04:55 UTC, maindishes commented on src/channels/channels.service.ts
> +      await this.cacheManager.set(key, kicklist, 50000);
저거 milliseconds 로 일단 5분 하는거 입니다. 나중에 ttl 이름이라는 인자로 받아서 설정 가능하게 할 예정 ( ttl *1000)  

2023-03-31 04:56 UTC, maindishes commented on src/channels/channels.service.ts
> +    const ban = await this.channelMuteMemberRepository.findOne({
수정 완료

2023-03-31 05:14 UTC, maindishes commented on src/channels/channels.controller.ts
> +  @Post('/room/:roomId/ban/:userId')
clear

2023-03-31 05:33 UTC, maindishes commented on src/channels/chats/chats.controller.ts
>  @ApiTags('CHAT')
Clear

2023-03-31 05:42 UTC, maindishes commented on src/channels/chats/chats.service.ts
> +      if (userId == 1) {
제 로컬엔 db에 유저가 없어서 주말중으로 연결 해서 완료할예정입니다

2023-03-31 05:42 UTC, maindishes commented on src/channels/chats/chats.service.ts
> +    this.channelsGateway.nsp.emit('message', chat);
맞습니다  이것도 일단 연결해서 직접 보내면서 테스트 후 수정할 예정 입니다

2023-04-01 10:35 UTC, minjune8506 approved these changes

2023-04-01 10:35 UTC, minjune8506 commented on src/channels/chats/chats.entity.ts
> +  receiverId: number;
얘는 또 nullable이 맞지않아요?

2023-04-02 08:37 UTC, maindishes commented on src/channels/chats/chats.entity.ts
> +  receiverId: number;
clear

2023-04-02 08:37 UTC, closed without merging