Feat/dm
42-TRANSENDENCE/backend pull request #134
Opened 2023-04-07 08:53 UTC by maindishes

- 현재 DB  상태 : 
  - Channel - Member, BanMember - User 
  - Member , BanMember 가 채널 과 User에 ManyToMany관계 
  
<img width="930" alt="image" src="https://user-images.githubusercontent.com/65796820/230572892-78365a5f-c524-4bf4-be1d-7933aed03c6e.png">

- TypeOrm Ban 멤버 관리 때문에 레퍼런스보고 커스텀 방법으로 ManyToOne , OneToMany 로 ManyToMany  구현  .
- 하는김에 멤버도 커스텀 방법으로 구현 
![image](https://user-images.githubusercontent.com/65796820/230577111-d2422a32-ce76-459b-b889-eb5017e8977a.png)

- DM 관련해서 SenderId 와 ReciveId를 어떻게 연결 할까 생각중 ..

2023-04-07 12:40 UTC, minjune8506 commented on src/channels/chats/chats.entity.ts
>    senderId: number;
OneToOne

2023-04-07 12:40 UTC, minjune8506 commented on src/channels/chats/chats.entity.ts
> +  @Column({ nullable: true }) // 얘도 유저 아이디랑 묶어야 겠다.
OneToOne

2023-04-07 12:42 UTC, minjune8506 commented on src/channels/chats/chats.entity.ts
> +  chats: Chats;
Chat이 아니라 Channel을 가지고 있어야 하는게 아닌지?
Chat: Channel = N : 1
ManyToOne은 맞음

2023-04-07 12:44 UTC, minjune8506 commented on src/channels/chats/chats.entity.ts
> +  dm: Chats;
dm을 따로 관리할 필요가 있을지..?c
Channel type: DM으로 설정해버리면 따로 처리가 필요없음

2023-04-08 02:46 UTC, maindishes commented on src/channels/chats/chats.entity.ts
> +  dm: Chats;
아 맞네요 DM 은 Channel type: PRIVATE , enum 으로 관리하고 있어서 따로 관리할 필요 없네요

2023-04-08 02:50 UTC, minjune8506 commented on src/channels/channelbanmember.entity.ts
> +    (channelBanMember) => channelBanMember.bannedMembers,
이건 channel 안에 있는 멤버로 해야하는거 아니에여?

2023-04-08 02:52 UTC, minjune8506 commented on src/channels/channels.controller.ts
>      @Param('userId') userId: number,
userId를 가져올 필요가 없습니다.

2023-04-08 02:52 UTC, minjune8506 commented on src/channels/channels.controller.ts
>      @Param('userId') userId: number,
여기도 마찬가지로

2023-04-08 02:52 UTC, minjune8506 commented on src/channels/channels.controller.ts
>  @Controller('/channels')
JwtTwoFactorGuard 사용하면 자동으로 User 정보를 가져오기 때문에
url에서 user id 안받아도 돼여

2023-04-08 02:53 UTC, minjune8506 commented on src/channels/channels.entity.ts
> +  status: ChatStatus;
channel의 상태인데 왜 이름은 Chat Status??

2023-04-08 02:54 UTC, minjune8506 commented on src/channels/channels.entity.ts
> +  dm: Chats[];
chat 이랑 dm을 따로 관리할 필요가 있을까요?
둘다 channel에 있는 메시지인건 다를게 없는데

2023-04-08 03:00 UTC, minjune8506 commented
DB 테이블 이름도 단수 / 복수 통일성 있는게 좋아보여요

2023-04-10 01:26 UTC, maindishes commented on src/channels/chats/chats.entity.ts
> +  chats: Chats;
아 이부분 수정 했습니다

2023-04-10 01:32 UTC, maindishes commented on src/channels/channels.controller.ts
>  @Controller('/channels')
그전에 잘 동작하는지 알아보기 위해 받아 왔는데 이제 삭제할 예쩡

2023-04-10 01:32 UTC, maindishes commented on src/channels/channels.controller.ts
>      @Param('userId') userId: number,
수정 완료

2023-04-10 01:32 UTC, maindishes commented on src/channels/channels.controller.ts
>      @Param('userId') userId: number,
수정완료

2023-04-10 01:44 UTC, maindishes commented on src/channels/channels.entity.ts
> +  status: ChatStatus;
ChannelStatus 로 수정 완료

2023-04-11 01:43 UTC, maindishes commented on src/channels/chats/chats.entity.ts
>    senderId: number;
이거 아무리 생각해도 ManyToOne 이 맞는거 같숨다

2023-04-11 01:44 UTC, maindishes commented on src/channels/channels.entity.ts
> +  dm: Chats[];
수정 완료 !

2023-04-11 01:45 UTC, maindishes commented on src/channels/chats/chats.entity.ts
>    senderId: number;
1번 채팅방에 유저 2 ~ N 명  @minjune8506

2023-04-11 01:51 UTC, minjune8506 commented on src/channels/chats/chats.entity.ts
>    senderId: number;
이거 메세지 아닌가요?

2023-04-11 02:02 UTC, maindishes commented on src/channels/chats/chats.entity.ts
>    senderId: number;
넵 메세지 맞습니다 .

2023-04-11 02:04 UTC, maindishes commented on src/channels/chats/chats.entity.ts
>    senderId: number;
채팅방 id :1 ,  channelId 가 1 인 메세지 컬럼들은 싹다 1 번 채팅방에서 보낸거

2023-04-11 02:17 UTC, minjune8506 commented on src/channels/chats/chats.entity.ts
>    senderId: number;
그건 channelId로 하는거 아닌가요
senderId는 user랑 매핑되는게 맞는거같은데
user : chat = 1 : N 이구나

2023-04-11 02:22 UTC, maindishes commented on src/channels/chats/chats.entity.ts
>    senderId: number;
네넵 그건 channelId 로 하는게  맞고 그안에 1번방에 대한 채팅방에 유저가 여러명(senderId) 있을수 있어서 user : chat = 1 : N

2023-04-11 04:06 UTC, minjune8506 requested changes

2023-04-11 04:06 UTC, minjune8506 commented on src/channels/channelbanmember.entity.ts
> +    (channelBanMember) => channelBanMember.bannedMembers,
@maindishes ?

2023-04-11 04:06 UTC, minjune8506 commented on src/channels/channelmember.entity.ts
> +  @ManyToOne(() => Channel, (channelMember) => channelMember.members, {
여기도 channel.members로 가야하는거 아니에요?

2023-04-11 04:06 UTC, minjune8506 commented on src/channels/channels.entity.ts
>    owner?: number;
owner도 결국 사용자 아닌지?

number가 아니라 User와 관계를 맺어야 할 것 같음

2023-04-11 04:06 UTC, minjune8506 commented on src/channels/channels.entity.ts
> +  @Column({ type: 'enum', enum: ChannelStatus, nullable: true })
channel의 status가 nullable일 수 있는지.?

2023-04-11 04:06 UTC, minjune8506 commented on src/channels/chats/chats.entity.ts
>    channelId: number;
channel : chat = 1 : N

chat에서도 channel에 접근하게 하고 싶으면 Channel을 갖고 있어야 하는거 아닌가요..?

channel Id를 가지고 있는건 뭔가 이상해보임

2023-04-11 04:06 UTC, minjune8506 commented on src/channels/chats/chats.entity.ts
>    receiverId?: number;
받는 사람의 id가 필요한지..?
channel 의 타입을 DM으로 해놓고 보낼거면
받는사람이 누구인지 알 필요가 없음.
채팅방에만 보내면 어짜피 DM이니까 둘밖에 없는 채팅방..!

2023-04-11 04:06 UTC, minjune8506 commented on src/channels/chats/chats.entity.ts
> +  chats: Channel;
chats: Channel ?
이게 뭐죠?

2023-04-11 04:10 UTC, maindishes commented on src/channels/channelbanmember.entity.ts
> +    (channelBanMember) => channelBanMember.bannedMembers,
밴이 되거나 Kick 을 하면 멤버에서 빼고 (채팅방 나가지고) 밴 Entity에 들어가는데 빼기 전에 멤버 확인하고 Ban에 넣고 member에서 빼면 그게 더 맞겠네요 , 어차피 채팅방에서만 Ban을 할수있으닌까 
수정 하겠습니당

2023-04-11 04:15 UTC, maindishes commented on src/channels/channelmember.entity.ts
> +  @ManyToOne(() => Channel, (channelMember) => channelMember.members, {
아직 수정 안 했는데 수정 할예정 입니다

2023-04-11 04:16 UTC, maindishes commented on src/channels/chats/chats.entity.ts
>    receiverId?: number;
아 이건 초기에 Home User가 가지고 있는 SocketID 로 바로  DM 보내는거 때문에 해놨는데 이제 채팅방 만들어서 하는거닌까 필요 없겠네요

2023-04-11 04:17 UTC, maindishes commented on src/channels/channels.entity.ts
>    owner?: number;
맞습니다 근데 그러면 Ban멤버와 비슷하게 이것도 channelMember와  관계를 맺어야 하지 않나요 ?

2023-04-11 04:17 UTC, maindishes commented on src/channels/chats/chats.entity.ts
>    receiverId?: number;
수정 하겠습니다  !

2023-04-11 05:14 UTC, minjune8506 commented on src/channels/channelbanmember.entity.ts
> +    (channelBanMember) => channelBanMember.bannedMembers,
아니아니 () => 이부분..

2023-04-11 05:15 UTC, minjune8506 commented on src/channels/channels.entity.ts
>    owner?: number;
oneToMany 아닌가여?

아 근데 channel member가 many to many로 테이블 만들었으니까 그냥 거기다가 type 필드 하나 만들면 되겠는데요?

2023-04-12 10:00 UTC, minjune8506 approved these changes

2023-04-12 10:02 UTC, merged